### ISSUE TITLE
misleading "generating docs under #{roots}/"

### ISSUE THREAD

**Issue by skierpage** [mbrevoort/docco-husky#13]
After `npm install docco-husky` (version 0.3.2) I ran `./node_modules/.bin/docco-husky myscript.js`.

It helpfully logs

```
docco: Recursively generating docs underneath myscript.js/
```

But obviously it can't do this since myscript.js is a file. It actually creates a docs/myscript.js.html. And appending a single / to the end of a set of files and directories makes no sense.  Maybe just change

``` coffee
    console.log "docco: Recursively generating docs underneath #{roots}/"
```

to

``` coffee
    console.log "docco: Generating documentation for #{roots}"
```

**Comment by mbrevoort** [comment]
Fixed. Thanks!
